import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const migrationsDir = join(root, "migrations");
export const outFile = join(root, "src/migrations.generated.ts");

/** Renders the migration folders into a runtime-agnostic TS module so the compiled CLI needs no files on disk. */
export async function renderMigrationsModule(): Promise<string> {
	const entries = await readdir(migrationsDir, { withFileTypes: true });
	const names = entries
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort();

	const rows = await Promise.all(
		names.map(async (name) => {
			const sql = await readFile(
				join(migrationsDir, name, "migration.sql"),
				"utf8"
			);
			return `\t${JSON.stringify(name)}: ${JSON.stringify(sql)},`;
		})
	);

	return [
		"// Generated by scripts/embed-migrations.ts from ../migrations. Do not edit.",
		"export const migrations: Record<string, string> = {",
		...rows,
		"};",
		"",
	].join("\n");
}

if (import.meta.main) {
	await writeFile(outFile, await renderMigrationsModule());
}
