/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as AuthDesktopRouteImport } from './routes/auth/desktop'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceWorkersIndexRouteImport } from './routes/_workspace/workers/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceSettingsSourceControlRouteImport } from './routes/_workspace/settings/source-control'
import { Route as WorkspaceSettingsProvidersRouteImport } from './routes/_workspace/settings/providers'
import { Route as WorkspaceSettingsKeybindingsRouteImport } from './routes/_workspace/settings/keybindings'
import { Route as WorkspaceSettingsConnectionsRouteImport } from './routes/_workspace/settings/connections'
import { Route as WorkspaceSettingsArchivedRouteImport } from './routes/_workspace/settings/archived'
import { Route as WorkspaceWorkersWorkerIdRouteRouteImport } from './routes/_workspace/workers/$workerId/route'
import { Route as WorkspaceWorkersWorkerIdIndexRouteImport } from './routes/_workspace/workers/$workerId/index'
import { Route as WorkspaceWorkersWorkerIdPIndexRouteImport } from './routes/_workspace/workers/$workerId/p/index'
import { Route as WorkspaceWorkersWorkerIdPProjectIdIndexRouteImport } from './routes/_workspace/workers/$workerId/p/$projectId/index'
import { Route as WorkspaceWorkersWorkerIdPProjectIdTIndexRouteImport } from './routes/_workspace/workers/$workerId/p/$projectId/t/index'
import { Route as WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRouteImport } from './routes/_workspace/workers/$workerId/p/$projectId/t/$threadId/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDesktopRoute = AuthDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceWorkersIndexRoute = WorkspaceWorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsSourceControlRoute =
  WorkspaceSettingsSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsProvidersRoute =
  WorkspaceSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsKeybindingsRoute =
  WorkspaceSettingsKeybindingsRouteImport.update({
    id: '/keybindings',
    path: '/keybindings',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsConnectionsRoute =
  WorkspaceSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsArchivedRoute =
  WorkspaceSettingsArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdRouteRoute =
  WorkspaceWorkersWorkerIdRouteRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdIndexRoute =
  WorkspaceWorkersWorkerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkersWorkerIdRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdPIndexRoute =
  WorkspaceWorkersWorkerIdPIndexRouteImport.update({
    id: '/p/',
    path: '/p/',
    getParentRoute: () => WorkspaceWorkersWorkerIdRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdPProjectIdIndexRoute =
  WorkspaceWorkersWorkerIdPProjectIdIndexRouteImport.update({
    id: '/p/$projectId/',
    path: '/p/$projectId/',
    getParentRoute: () => WorkspaceWorkersWorkerIdRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdPProjectIdTIndexRoute =
  WorkspaceWorkersWorkerIdPProjectIdTIndexRouteImport.update({
    id: '/p/$projectId/t/',
    path: '/p/$projectId/t/',
    getParentRoute: () => WorkspaceWorkersWorkerIdRouteRoute,
  } as any)
const WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute =
  WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRouteImport.update({
    id: '/p/$projectId/t/$threadId/',
    path: '/p/$projectId/t/$threadId/',
    getParentRoute: () => WorkspaceWorkersWorkerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/success': typeof AuthSuccessRoute
  '/workers/$workerId': typeof WorkspaceWorkersWorkerIdRouteRouteWithChildren
  '/settings/archived': typeof WorkspaceSettingsArchivedRoute
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/keybindings': typeof WorkspaceSettingsKeybindingsRoute
  '/settings/providers': typeof WorkspaceSettingsProvidersRoute
  '/settings/source-control': typeof WorkspaceSettingsSourceControlRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/workers/': typeof WorkspaceWorkersIndexRoute
  '/workers/$workerId/': typeof WorkspaceWorkersWorkerIdIndexRoute
  '/workers/$workerId/p/': typeof WorkspaceWorkersWorkerIdPIndexRoute
  '/workers/$workerId/p/$projectId/': typeof WorkspaceWorkersWorkerIdPProjectIdIndexRoute
  '/workers/$workerId/p/$projectId/t/': typeof WorkspaceWorkersWorkerIdPProjectIdTIndexRoute
  '/workers/$workerId/p/$projectId/t/$threadId/': typeof WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/success': typeof AuthSuccessRoute
  '/settings/archived': typeof WorkspaceSettingsArchivedRoute
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/keybindings': typeof WorkspaceSettingsKeybindingsRoute
  '/settings/providers': typeof WorkspaceSettingsProvidersRoute
  '/settings/source-control': typeof WorkspaceSettingsSourceControlRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/workers': typeof WorkspaceWorkersIndexRoute
  '/workers/$workerId': typeof WorkspaceWorkersWorkerIdIndexRoute
  '/workers/$workerId/p': typeof WorkspaceWorkersWorkerIdPIndexRoute
  '/workers/$workerId/p/$projectId': typeof WorkspaceWorkersWorkerIdPProjectIdIndexRoute
  '/workers/$workerId/p/$projectId/t': typeof WorkspaceWorkersWorkerIdPProjectIdTIndexRoute
  '/workers/$workerId/p/$projectId/t/$threadId': typeof WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/success': typeof AuthSuccessRoute
  '/_workspace/workers/$workerId': typeof WorkspaceWorkersWorkerIdRouteRouteWithChildren
  '/_workspace/settings/archived': typeof WorkspaceSettingsArchivedRoute
  '/_workspace/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/_workspace/settings/keybindings': typeof WorkspaceSettingsKeybindingsRoute
  '/_workspace/settings/providers': typeof WorkspaceSettingsProvidersRoute
  '/_workspace/settings/source-control': typeof WorkspaceSettingsSourceControlRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/_workspace/workers/': typeof WorkspaceWorkersIndexRoute
  '/_workspace/workers/$workerId/': typeof WorkspaceWorkersWorkerIdIndexRoute
  '/_workspace/workers/$workerId/p/': typeof WorkspaceWorkersWorkerIdPIndexRoute
  '/_workspace/workers/$workerId/p/$projectId/': typeof WorkspaceWorkersWorkerIdPProjectIdIndexRoute
  '/_workspace/workers/$workerId/p/$projectId/t/': typeof WorkspaceWorkersWorkerIdPProjectIdTIndexRoute
  '/_workspace/workers/$workerId/p/$projectId/t/$threadId/': typeof WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/device'
    | '/auth/success'
    | '/workers/$workerId'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/'
    | '/workers/'
    | '/workers/$workerId/'
    | '/workers/$workerId/p/'
    | '/workers/$workerId/p/$projectId/'
    | '/workers/$workerId/p/$projectId/t/'
    | '/workers/$workerId/p/$projectId/t/$threadId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/device'
    | '/auth/success'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings'
    | '/workers'
    | '/workers/$workerId'
    | '/workers/$workerId/p'
    | '/workers/$workerId/p/$projectId'
    | '/workers/$workerId/p/$projectId/t'
    | '/workers/$workerId/p/$projectId/t/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/auth'
    | '/_workspace/settings'
    | '/auth/callback'
    | '/auth/desktop'
    | '/auth/device'
    | '/auth/success'
    | '/_workspace/workers/$workerId'
    | '/_workspace/settings/archived'
    | '/_workspace/settings/connections'
    | '/_workspace/settings/keybindings'
    | '/_workspace/settings/providers'
    | '/_workspace/settings/source-control'
    | '/_workspace/settings/'
    | '/_workspace/workers/'
    | '/_workspace/workers/$workerId/'
    | '/_workspace/workers/$workerId/p/'
    | '/_workspace/workers/$workerId/p/$projectId/'
    | '/_workspace/workers/$workerId/p/$projectId/t/'
    | '/_workspace/workers/$workerId/p/$projectId/t/$threadId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/desktop': {
      id: '/auth/desktop'
      path: '/desktop'
      fullPath: '/auth/desktop'
      preLoaderRoute: typeof AuthDesktopRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/workers/': {
      id: '/_workspace/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkspaceWorkersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/source-control': {
      id: '/_workspace/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof WorkspaceSettingsSourceControlRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/providers': {
      id: '/_workspace/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof WorkspaceSettingsProvidersRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/keybindings': {
      id: '/_workspace/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof WorkspaceSettingsKeybindingsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/connections': {
      id: '/_workspace/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof WorkspaceSettingsConnectionsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/archived': {
      id: '/_workspace/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof WorkspaceSettingsArchivedRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/workers/$workerId': {
      id: '/_workspace/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/workers/$workerId/': {
      id: '/_workspace/workers/$workerId/'
      path: '/'
      fullPath: '/workers/$workerId/'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkersWorkerIdRouteRoute
    }
    '/_workspace/workers/$workerId/p/': {
      id: '/_workspace/workers/$workerId/p/'
      path: '/p'
      fullPath: '/workers/$workerId/p/'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdPIndexRouteImport
      parentRoute: typeof WorkspaceWorkersWorkerIdRouteRoute
    }
    '/_workspace/workers/$workerId/p/$projectId/': {
      id: '/_workspace/workers/$workerId/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/workers/$workerId/p/$projectId/'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdPProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkersWorkerIdRouteRoute
    }
    '/_workspace/workers/$workerId/p/$projectId/t/': {
      id: '/_workspace/workers/$workerId/p/$projectId/t/'
      path: '/p/$projectId/t'
      fullPath: '/workers/$workerId/p/$projectId/t/'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdPProjectIdTIndexRouteImport
      parentRoute: typeof WorkspaceWorkersWorkerIdRouteRoute
    }
    '/_workspace/workers/$workerId/p/$projectId/t/$threadId/': {
      id: '/_workspace/workers/$workerId/p/$projectId/t/$threadId/'
      path: '/p/$projectId/t/$threadId'
      fullPath: '/workers/$workerId/p/$projectId/t/$threadId/'
      preLoaderRoute: typeof WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkersWorkerIdRouteRoute
    }
  }
}

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsArchivedRoute: typeof WorkspaceSettingsArchivedRoute
  WorkspaceSettingsConnectionsRoute: typeof WorkspaceSettingsConnectionsRoute
  WorkspaceSettingsKeybindingsRoute: typeof WorkspaceSettingsKeybindingsRoute
  WorkspaceSettingsProvidersRoute: typeof WorkspaceSettingsProvidersRoute
  WorkspaceSettingsSourceControlRoute: typeof WorkspaceSettingsSourceControlRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsArchivedRoute: WorkspaceSettingsArchivedRoute,
    WorkspaceSettingsConnectionsRoute: WorkspaceSettingsConnectionsRoute,
    WorkspaceSettingsKeybindingsRoute: WorkspaceSettingsKeybindingsRoute,
    WorkspaceSettingsProvidersRoute: WorkspaceSettingsProvidersRoute,
    WorkspaceSettingsSourceControlRoute: WorkspaceSettingsSourceControlRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceWorkersWorkerIdRouteRouteChildren {
  WorkspaceWorkersWorkerIdIndexRoute: typeof WorkspaceWorkersWorkerIdIndexRoute
  WorkspaceWorkersWorkerIdPIndexRoute: typeof WorkspaceWorkersWorkerIdPIndexRoute
  WorkspaceWorkersWorkerIdPProjectIdIndexRoute: typeof WorkspaceWorkersWorkerIdPProjectIdIndexRoute
  WorkspaceWorkersWorkerIdPProjectIdTIndexRoute: typeof WorkspaceWorkersWorkerIdPProjectIdTIndexRoute
  WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute: typeof WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute
}

const WorkspaceWorkersWorkerIdRouteRouteChildren: WorkspaceWorkersWorkerIdRouteRouteChildren =
  {
    WorkspaceWorkersWorkerIdIndexRoute: WorkspaceWorkersWorkerIdIndexRoute,
    WorkspaceWorkersWorkerIdPIndexRoute: WorkspaceWorkersWorkerIdPIndexRoute,
    WorkspaceWorkersWorkerIdPProjectIdIndexRoute:
      WorkspaceWorkersWorkerIdPProjectIdIndexRoute,
    WorkspaceWorkersWorkerIdPProjectIdTIndexRoute:
      WorkspaceWorkersWorkerIdPProjectIdTIndexRoute,
    WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute:
      WorkspaceWorkersWorkerIdPProjectIdTThreadIdIndexRoute,
  }

const WorkspaceWorkersWorkerIdRouteRouteWithChildren =
  WorkspaceWorkersWorkerIdRouteRoute._addFileChildren(
    WorkspaceWorkersWorkerIdRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceWorkersWorkerIdRouteRoute: typeof WorkspaceWorkersWorkerIdRouteRouteWithChildren
  WorkspaceWorkersIndexRoute: typeof WorkspaceWorkersIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceWorkersWorkerIdRouteRoute:
    WorkspaceWorkersWorkerIdRouteRouteWithChildren,
  WorkspaceWorkersIndexRoute: WorkspaceWorkersIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDesktopRoute: typeof AuthDesktopRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDesktopRoute: AuthDesktopRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  AuthSuccessRoute: AuthSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
